--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/LaunchACM
build-by-default: true
branches:
- PM4
projects:
  LaunchACM:
    path: ""
    icon: icon-acm.png
    lint:
      phpstan: false
...
