--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/LaunchACM
build-by-default: true
branches:
- PM5
- PM4
projects:
  LaunchACM:
    path: ""
    icon: icon-acm.png
    libs:
      - src: ACM-PocketMine-MP/libPiggyUpdateChecker/libPiggyUpdateChecker
        version: ^2.0.0
    lint:
      phpstan: false
...
