#   _                                      _          _       ____   __  __ 
#  | |       __ _   _   _   _ __     ___  | |__      / \     / ___| |  \/  |
#  | |      / _` | | | | | | '_ \   / __| | '_ \    / _ \   | |     | |\/| |
#  | |___  | (_| | | |_| | | | | | | (__  | | | |  / ___ \  | |___  | |  | |
#  |_____|  \__,_|  \__,_| |_| |_|  \___| |_| |_| /_/   \_\  \____| |_|  |_|
                                                                          
#           by fernanACM
# The best launchpad for PocketMine-MP 4.0, easy to use.
# The best launch release for Pocketmine-MP 4.0, easy to use.
# It adds fun sounds that you can configure in the 'config.yml'. This is the page for the sounds:
# https://www.digminecraft.com/lists/sound_list_pe.php

# ========(CONFIGURATION)========
Settings:
  # Disable the worlds where you don't want the launchpad not to work. 
  disabled-worlds:
    - world1
    - FFA
  # Add the amount of thrust you want for the LaunchPad, 
  # example: 1, 2, 3, 4, 5, 6...
  knockback-amount: 1
  # Use "true" or "false" to activate/disable sound option when using the launchpad
  launchpad-no-sound: true
  # The sounds can be found at: https://www.digminecraft.com/lists/sound_list_pe.php
  # Add the type of sound you want for the launchpad, example: "random.click"
  launchpad-sound: "mob.irongolem.walk"
# ========(TYPES OF lAUNCHPADS)========
LaunchPad:
  # Use "True or" false "to activate/disable the use of this launchpad
  # Type: Stone
  StonePressurePlate: true
  # Use "True or" false "to activate/disable the use of this launchpad
  # Type: Oak
  OakPressurePlate: true
  # Use "True or" false "to activate/disable the use of this launchpad
  # Type: Acacia
  AcaciaPressurePlate: true
  # Use "True or" false "to activate/disable the use of this launchpad
  # Type: Birch
  BirchPressurePlate: true
  # Use "True or" false "to activate/disable the use of this launchpad
  # Type: Dark Oak
  DarkOakPressurePlate: true
  # Use "True or" false "to activate/disable the use of this launchpad
  # Type: Jungle
  JunglePressurePlate: true
  # Use "True or" false "to activate/disable the use of this launchpad
  # Type: Spruce
  SprucePressurePlate: true
  # Use "True or" false "to activate/disable the use of this launchpad
  # Type: Light Weighted
  LightWeightedPressurePlate: true
  # Use "True or" false "to activate/disable the use of this launchpad
  # Type: Heavy Weighted
  HeavyWeightedPressurePlate: true
